name:                texpr
version:             0.1.0.0
github:              "githubuser/texpr"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/texpr#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- random
# - hegg
- prettyprinter
- text
- containers
- vector
- megaparsec
- hashable

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules: 
    - TExpr2
    - IExpr
    - Util

executables:
  texpr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - texpr
    - pretty-simple

tests:
  test:
    main: Driver.hs
    source-dirs: test/test
    dependencies:
    - texpr
    - tasty
    - tasty-hunit
    - tasty-discover
    - tasty-quickcheck


default-extensions: OverloadedStrings, LambdaCase
